// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSniFrSjChJz0afJEIJ96CQHbvDPCTQdo',
    appId: '1:34516377367:web:572409b16fdaad1c44a152',
    messagingSenderId: '34516377367',
    projectId: 'streamed-chat',
    authDomain: 'streamed-chat.firebaseapp.com',
    storageBucket: 'streamed-chat.appspot.com',
    measurementId: 'G-BZGFG6TLJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORWlElj1q4IKc5cR42aPXsJXHy96GKn4',
    appId: '1:34516377367:android:29fa5dd769abb61444a152',
    messagingSenderId: '34516377367',
    projectId: 'streamed-chat',
    storageBucket: 'streamed-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjChDYLKIuvRPbS82IFDo1oXLbsRoCdfk',
    appId: '1:34516377367:ios:3b85d1ea937af6ab44a152',
    messagingSenderId: '34516377367',
    projectId: 'streamed-chat',
    storageBucket: 'streamed-chat.appspot.com',
    iosBundleId: 'com.example.chatBySocketSamle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSniFrSjChJz0afJEIJ96CQHbvDPCTQdo',
    appId: '1:34516377367:web:e46d9667a8f9307d44a152',
    messagingSenderId: '34516377367',
    projectId: 'streamed-chat',
    authDomain: 'streamed-chat.firebaseapp.com',
    storageBucket: 'streamed-chat.appspot.com',
    measurementId: 'G-V9MS9B4196',
  );

}